### ISSUE TITLE
attribute error queue

### ISSUE THREAD

**Issue by arronlacey** [pradeepvemulakonda/Snomed#2]
HI pradeep - I'm getting the following error:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/arron/Downloads/Snomed/worker/neo4j_upload_worker.py", line 36, in run
    self.queue.task_done()
AttributeError: 'Queue' object has no attribute 'task_done'

and using python 3.4.3 and py2neo 2.0.9.

have you come across this?
```

**Comment by pradeepvemulakonda** [comment]
Hi Arron, will look into it and get back to you. There is a groovy version of the same, that I recently updated, you can try that as well.

**Comment by arronlacey** [comment]
HI Pradeep - I've just had a further look and I had conflicting python libraries. Am now running within virtual env with clean python 3.4.3 install. all fine now.

so just to reiterate again this works on linux mint 17 with python 3.4.3 and py2neo 2.0.9.

this is a great app by the way.

**Comment by pradeepvemulakonda** [comment]
Thanks for the environment details, I will update the same in the reader.
