### ISSUE TITLE
could not convert string to float: 'id'

### ISSUE THREAD

**Issue by arronlacey** [pradeepvemulakonda/Snomed#3]
Hi Pradeep -do you get this error?:

```
Traceback (most recent call last):
  File "run_snomed_upload.py", line 84, in <module>
    rte.execute(sg, sp)
  File "/home/arron/Downloads/Snomed/worker/thread_executor.py", line 27, in execute
    for item in item_generator.generate:
  File "/usr/lib/python3.4/csv.py", line 109, in __next__
    self.fieldnames
  File "/usr/lib/python3.4/csv.py", line 96, in fieldnames
    self._fieldnames = next(self.reader)
ValueError: could not convert string to float: 'id'
```

data is like - 

```
|id|,|effectiveTime|,|active|,|moduleId|,|sourceId|,|destinationId|,|relationshipGroup|,|typeId|,|characteristicTypeId|,|modifierId|,|term|,|descType|,|relLabel|
|100022|,|20090731|,|0|,|900000000000207008|,|100000000|,|102272007|,|0|,|116680003|,|900000000000011006|,|900000000000451002|,|Is a (attribute)|,|900000000000003001|,|IS_A|
|101021|,|20020131|,|1|,|900000000000207008|,|10000006|,|29857009|,|0|,|116680003|,|900000000000011006|,|900000000000451002|,|Is a (attribute)|,|900000000000003001|,|IS_A|
|102025|,|20020131|,|1|,|900000000000207008|,|10000006|,|9972008|,|0|,|116680003|,|900000000000011006|,|900000000000451002|,|Is a (attribute)|,|900000000000003001|,|IS_A|
|103024|,|20030131|,|0|,|900000000000207008|,|1000004|,|19130008|,|0|,|116680003|,|900000000000011006|,|900000000000451002|,|Is a (attribute)|,|900000000000003001|,|IS_A|
```

and same quote/delimiter format put into snomed_concept_processor.py (which works fine).

**Comment by pradeepvemulakonda** [comment]
Hi Arron,

    I am setting up the project in my mac and see I would face the same issue.It had been nearly 2 years since I wrote this code and I vaguely remember encountering this error. Will update you with the details on this error if I encountered the same.

Thanks,
Pradeep V B

**Comment by pradeepvemulakonda** [comment]
Hi Arron,

    I have upgraded the master branch to use Python 3.6.1 and py2neo 3.1.2. The code runs fine in a virtualenv on Mac and was able to upload the entire snomed international edition. Took some time for the relationships to upload. I did not face the specified error. I am adding a step by step setup of my dev environment, please check the same and provide your inputs(my primary skills are in Java).

Thank you,
Pradeep V B

**Comment by pradeepvemulakonda** [comment]
Hi Arron,

     I have upgraded the main branch to use Python 3.6.1 and py2neo 3.1.2. I am using the new bolt protocol for uploading the data and increased the no of threads to 20. The code is working and I had successfully uploaded Snomed-ct international data.

Thank you,
Pradeep V B

**Comment by arronlacey** [comment]
updated to python 3.6.1

```
upload of snomed synonyms complete
--- time taken to upload synonyms 1825.391284942627 seconds ---
upload snomed relationships started..
Going to take approximately 1.5 hours... grab a coffee .. and relax
Starting threads: 1
reading files
In the finally
in the worker finally
Traceback (most recent call last):
  File "run_snomed_upload.py", line 84, in <module>
    rte.execute(sg, sp)
  File "/home/arron/Downloads/Snomed/worker/thread_executor.py", line 27, in execute
    for item in item_generator.generate:
  File "/usr/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/usr/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
ValueError: could not convert string to float: 'id'
```


I think it must be an issue with the input file. I am using the files found at:

https://www.nlm.nih.gov/healthit/snomedct/international.html




as a side not when I use py2neo3.1.2 I get:
`
AttributeError: 'Graph' object has no attribute 'cypher'`

but works fine with py2neo2.0.8.

**Comment by pradeepvemulakonda** [comment]
Hi Arron, the cypher error is because there are some changes in the code for py2neo version 3.1.2. Please get the new code from master branch. Can you please check the file that has been generated in the results folder? I am using the same snomed international files. Not sure if you are a python programmer, but you can use pycharm to debug the code, you can find why the conversion error keeps coming. Initially try with the new code, I am updating on wiki on how to setup the Dev environment which might help you in finding the error.
